// restore_form.js — restores corrupted Hebrew mortgage form in MongoDB Atlas
// Usage: node restore_form.js
'use strict';

require('dotenv').config();
const mongoose = require('mongoose');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/forms-saas';

const FormSchema = new mongoose.Schema({
  id:          { type: String, required: true, unique: true },
  tenantId:    { type: String, default: 'default' },
  title:       { type: String, default: '' },
  description: { type: String, default: '' },
  questions:   { type: Array,  default: [] },
  createdAt:   { type: String },
  updatedAt:   { type: String },
}, { strict: false });

const Form = mongoose.model('Form', FormSchema);

// ── Hebrew label mapping ──────────────────────────────────────────────────────
const LABELS = {
  b_count: 'כמה לווים יש בעסקה?',
  guar_exists: 'האם יש ערב בעסקה?',
  b1_fname: 'שם פרטי',
  b1_lname: 'שם משפחה',
  b1_id: 'תעודת זהות',
  b1_dob: 'תאריך לידה',
  b1_gender: 'מין',
  b1_marital: 'מצב משפחתי',
  b1_children: 'מספר ילדים',
  b1_phone: 'טלפון נייד',
  b1_email: 'כתובת אימייל',
  b1_address: 'כתובת מגורים (רחוב ומספר)',
  b1_city: 'עיר מגורים',
  b1_zip: 'מיקוד',
  b1_citizen: 'אזרחות',
  b1_passno: 'מספר דרכון (אם רלוונטי)',
  b1_separation: 'האם יש הסכם ממון / גירושין בתהליך?',
  b1_poa: 'האם יש ייפוי כוח נוטריוני?',
  b1_employ_status: 'סטטוס תעסוקה',
  b1_employ_type: 'סוג מעסיק',
  b1_employer: 'שם המעסיק',
  b1_seniority: 'ותק במקום עבודה (בשנים)',
  b1_income: 'הכנסה חודשית נטו (ש"ח)',
  b1_extra_income: 'האם יש הכנסות נוספות?',
  b1_extra_detail: 'פרט הכנסות נוספות',
  b1_miluim: 'האם מקבל/ת מענק מילואים?',
  b1_pension: 'האם יש קצבת פנסיה?',
  b1_pension_amt: 'סכום קצבת הפנסיה (ש"ח)',
  b1_foreign_income: 'האם יש הכנסה ממקור זר?',
  b1_alimony: 'האם משלם/ת מזונות?',
  b1_alimony_amt: 'סכום המזונות החודשי (ש"ח)',
  b1_income_change: 'האם צפויה שינוי בהכנסה?',
  b1_income_change_detail: 'פרט שינוי הכנסה צפוי',
  b1_bank: 'בנק חשבון עיקרי',
  b1_account: 'מספר חשבון',
  doc_b1_id: 'צילום תעודת זהות (כולל ספח)',
  doc_b1_salary: 'תלושי שכר 3 חודשים אחרונים',
  doc_b1_bank: 'דפי בנק 3 חודשים אחרונים',
  guar_fname: 'שם פרטי של הערב',
  guar_lname: 'שם משפחה של הערב',
  guar_id: 'תעודת זהות של הערב',
  guar_phone: 'טלפון הערב',
  guar_email: 'אימייל הערב',
  guar_relation: 'קרבה ללווים',
  doc_guar_id: 'צילום תעודת זהות — ערב',
  ln1_exists: 'האם יש הלוואה נוספת ראשונה?',
  ln1_lender: 'שם הגוף המלווה',
  ln1_balance: 'יתרת ההלוואה (ש"ח)',
  ln1_monthly: 'תשלום חודשי (ש"ח)',
  ln1_end_date: 'תאריך סיום ההלוואה',
  ln1_purpose: 'מטרת ההלוואה',
  ln2_exists: 'האם יש הלוואה שנייה?',
  ln2_lender: 'שם הגוף המלווה',
  ln2_balance: 'יתרת ההלוואה (ש"ח)',
  ln2_monthly: 'תשלום חודשי (ש"ח)',
  ln2_end_date: 'תאריך סיום',
  ln2_purpose: 'מטרת ההלוואה',
  ln3_exists: 'האם יש הלוואה שלישית?',
  ln3_lender: 'שם הגוף המלווה',
  ln3_balance: 'יתרת ההלוואה (ש"ח)',
  ln3_monthly: 'תשלום חודשי (ש"ח)',
  ln3_end_date: 'תאריך סיום',
  ln3_purpose: 'מטרת ההלוואה',
  ln4_exists: 'האם יש הלוואה רביעית?',
  ln4_lender: 'שם הגוף המלווה',
  ln4_balance: 'יתרת ההלוואה (ש"ח)',
  ln4_monthly: 'תשלום חודשי (ש"ח)',
  ln4_end_date: 'תאריך סיום',
  ln4_purpose: 'מטרת ההלוואה',
  mt1_exists: 'האם יש משכנתא קיימת ראשונה?',
  mt1_bank: 'שם הבנק',
  mt1_balance: 'יתרת המשכנתא (ש"ח)',
  mt1_monthly: 'תשלום חודשי (ש"ח)',
  mt1_end_date: 'תאריך סיום',
  mt1_address: 'כתובת הנכס הממושכן',
  mt2_exists: 'האם יש משכנתא קיימת שנייה?',
  mt2_bank: 'שם הבנק',
  mt2_balance: 'יתרת המשכנתא (ש"ח)',
  mt2_monthly: 'תשלום חודשי (ש"ח)',
  mt2_end_date: 'תאריך סיום',
  mt2_address: 'כתובת הנכס הממושכן',
  mt3_exists: 'האם יש משכנתא קיימת שלישית?',
  mt3_bank: 'שם הבנק',
  mt3_balance: 'יתרת המשכנתא (ש"ח)',
  mt3_monthly: 'תשלום חודשי (ש"ח)',
  mt3_end_date: 'תאריך סיום',
  mt3_address: 'כתובת הנכס הממושכן',
  cc_count: 'מספר כרטיסי אשראי',
  cc_limit: 'מסגרת כרטיסי אשראי כוללת (ש"ח)',
  cc_balance: 'יתרת חוב כרטיסי אשראי (ש"ח)',
  guarantee_given: 'האם ניתנו ערבויות לאחרים?',
  guarantee_detail: 'פרט ערבויות',
  balloon_loan: 'האם יש הלוואת בלון?',
  balloon_detail: 'פרט הלוואת בלון',
  seizure: 'האם קיים עיקול?',
  seizure_detail: 'פרט עיקולים',
  bank_restrict: 'האם קיימות הגבלות בנקאיות?',
  bank_restrict_detail: 'פרט הגבלות',
  insolvency: 'האם הוכרז חדלות פירעון בעבר?',
  enforcement: 'האם קיים תיק בהוצאה לפועל?',
  enforcement_detail: 'פרט תיק הוצאה לפועל',
  debt_arrange: 'האם בוצע הסדר חובות?',
  debt_arrange_detail: 'פרט הסדר החובות',
  bounced_checks: 'האם היו המחאות חוזרות?',
  credit_denied: 'האם נדחתה בקשת אשראי בעבר?',
  legal_proc: 'האם ניהלת הליך משפטי הקשור לנכס?',
  legal_proc_detail: 'פרט הליך משפטי',
  doc_extra: 'מסמכים נוספים',
  declaration: 'הצהרת נכונות המידע',
  loan_type: 'סוג ההלוואה המבוקשת',
  prop_type: 'סוג הנכס',
  prop_status: 'מצב הנכס',
  prop_deal_type: 'סוג העסקה',
  prop_city: 'עיר / ישוב',
  prop_street: 'רחוב',
  prop_house_num: 'מספר בית',
  prop_apt_num: 'מספר דירה',
  prop_floor: 'קומה',
  prop_floors_total: 'סה"כ קומות בבניין',
  prop_rooms: 'מספר חדרים',
  prop_built_area: 'שטח בנוי (מ"ר)',
  prop_balcony_area: 'שטח מרפסת (מ"ר)',
  prop_garden_area: 'שטח גינה (מ"ר)',
  prop_parking: 'חנייה',
  prop_storage: 'מחסן',
  prop_elevator: 'מעלית',
  prop_year_built: 'שנת בניה',
  prop_registration: 'רישום',
  prop_rights: 'זכויות בנכס',
  prop_rented: 'האם הנכס מושכר?',
  prop_violations: 'האם ידוע על חריגות בנייה?',
  prop_violations_detail: 'פרט חריגות בנייה',
  deal_seller_type: 'סוג המוכר',
  deal_price: 'מחיר העסקה (ש"ח)',
  deal_mortgage_req: 'סכום המשכנתא המבוקש (ש"ח)',
  deal_contract_signed: 'האם נחתם חוזה?',
  deal_contract_date: 'תאריך חתימת חוזה',
  deal_conditions: 'האם יש תנאים מתלים בחוזה?',
  deal_conditions_detail: 'פרט תנאים מתלים',
  deal_advance_paid: 'האם שולמה מקדמה?',
  deal_advance_amount: 'סכום המקדמה (ש"ח)',
  deal_advance_date: 'תאריך תשלום מקדמה',
  deal_key_date: 'תאריך קבלת מפתח',
  deal_payment_sched: 'האם יש לוח תשלומים?',
  deal_payment_sched_detail: 'פרט לוח תשלומים',
  deal_status: 'מצב העסקה',
  eq_amount: 'סכום ההון העצמי (ש"ח)',
  eq_source: 'מקורות ההון העצמי',
  eq_gift: 'האם חלק מההון העצמי הוא מתנה?',
  eq_gift_name: 'שם נותן המתנה',
  eq_gift_relation: 'קרבה לנותן המתנה',
  eq_gift_amount: 'סכום המתנה (ש"ח)',
  eq_bridge: 'האם נדרש הלוואת גישור?',
  eq_bridge_amount: 'סכום הלוואת גישור (ש"ח)',
  eq_external: 'האם יש מממן חיצוני?',
  eq_external_funder: 'שם המממן החיצוני',
  eq_external_amount: 'סכום מהמממן החיצוני (ש"ח)',
  eq_prop_sale_dep: 'האם ההון תלוי במכירת נכס?',
  eq_prop_sale_detail: 'פרט תלות במכירת נכס',
  bkr_exists: 'האם יש מתווך נדל"ן?',
  bkr_fee: 'עמלת המתווך (%)',
  law_exists: 'האם יש עורך דין?',
  law_name: 'שם עורך הדין',
  law_phone: 'טלפון עורך הדין',
  apr_done: 'האם בוצעה שמאות?',
  apr_value: 'שווי שמאות (ש"ח)',
  apr_eligibility: 'האם יש זכאות?',
  apr_urgent: 'האם הבקשה דחופה?',
  doc_lrm_contract: 'חוזה רכישה',
  doc_lrm_taboo: 'נסח טאבו / אישור זכויות',
  doc_lrm_payments: 'אסמכתאות תשלומים',
  doc_lrm_appraisal: 'שמאות',
  doc_lrm_eligibility: 'אישור זכאות',
  doc_lrm_extra: 'מסמכים נוספים',
  inv_prop_type: 'סוג הנכס להשקעה',
  inv_prop_status: 'מצב הנכס',
  inv_prop_deal_type: 'סוג העסקה',
  inv_prop_city: 'עיר / ישוב',
  inv_prop_street: 'רחוב',
  inv_prop_house_num: 'מספר בית',
  inv_prop_apt_num: 'מספר דירה',
  inv_prop_rooms: 'מספר חדרים',
  inv_prop_built_area: 'שטח בנוי (מ"ר)',
  inv_prop_parking: 'חנייה',
  inv_prop_storage: 'מחסן',
  inv_prop_elevator: 'מעלית',
  inv_prop_rented: 'האם הנכס מושכר?',
  inv_prop_rent_amount: 'סכום שכירות חודשי (ש"ח)',
  inv_prop_violations: 'האם ידוע על חריגות בנייה?',
  inv_prop_violations_detail: 'פרט חריגות',
  inv_deal_seller_type: 'סוג המוכר',
  inv_deal_price: 'מחיר העסקה (ש"ח)',
  inv_deal_mortgage_req: 'סכום המשכנתא המבוקש (ש"ח)',
  inv_deal_contract_signed: 'האם נחתם חוזה?',
  inv_deal_contract_date: 'תאריך חתימת חוזה',
  inv_deal_advance_paid: 'האם שולמה מקדמה?',
  inv_deal_advance_amount: 'סכום המקדמה (ש"ח)',
  inv_deal_advance_date: 'תאריך תשלום מקדמה',
  inv_deal_key_date: 'תאריך קבלת מפתח',
  inv_deal_payment_sched: 'האם יש לוח תשלומים?',
  inv_deal_payment_sched_detail: 'פרט לוח תשלומים',
  inv_rental_intent: 'האם בכוונתך להשכיר את הנכס?',
  inv_expected_rent: 'שכירות חודשית צפויה (ש"ח)',
  inv_purpose: 'מטרת ההשקעה',
  inv_other_props: 'האם יש נכסים נוספים בבעלותך?',
  inv_other_props_count: 'כמה נכסים נוספים?',
  inv_other_props_mortgage: 'האם יש משכנתא על נכסים נוספים?',
  inv_other_props_monthly: 'סה"כ תשלומי משכנתא על נכסים נוספים (ש"ח)',
  inv_via_company: 'האם הרכישה דרך חברה?',
  inv_company_name: 'שם החברה',
  inv_company_id: 'מספר ח"פ',
  inv_partners: 'האם יש שותפים ברכישה?',
  inv_partners_count: 'מספר שותפים',
  inv_registration_name: 'על שם מי ירשם הנכס?',
  inv_eq_amount: 'סכום ההון העצמי להשקעה (ש"ח)',
  inv_eq_source: 'מקורות ההון העצמי',
  inv_eq_gift: 'האם חלק מההון הוא מתנה?',
  inv_eq_gift_name: 'שם נותן המתנה',
  inv_eq_gift_relation: 'קרבה לנותן המתנה',
  inv_eq_gift_amount: 'סכום המתנה (ש"ח)',
  inv_eq_bridge: 'האם נדרש הלוואת גישור?',
  inv_eq_bridge_amount: 'סכום הלוואת גישור (ש"ח)',
  inv_eq_external: 'האם יש מממן חיצוני?',
  inv_eq_external_funder: 'שם המממן',
  inv_eq_external_amount: 'סכום מהמממן (ש"ח)',
  inv_bkr_exists: 'האם יש מתווך?',
  inv_bkr_fee: 'עמלת מתווך (%)',
  inv_law_exists: 'האם יש עורך דין?',
  inv_law_name: 'שם עורך הדין',
  inv_law_phone: 'טלפון עורך הדין',
  inv_apr_done: 'האם בוצעה שמאות?',
  inv_apr_value: 'שווי שמאות (ש"ח)',
  doc_inv_contract: 'חוזה רכישה',
  doc_inv_taboo: 'נסח טאבו / אישור זכויות',
  doc_inv_payments: 'אסמכתאות תשלומים',
  doc_inv_appraisal: 'שמאות',
  doc_inv_rental: 'הסכם שכירות קיים',
  doc_inv_extra: 'מסמכים נוספים',
  imp_exist_prop_type: 'סוג הנכס הקיים',
  imp_exist_city: 'עיר הנכס הקיים',
  imp_exist_street: 'רחוב',
  imp_exist_house_num: 'מספר בית',
  imp_exist_apt_num: 'מספר דירה',
  imp_exist_value: 'שווי הנכס הקיים (ש"ח)',
  imp_exist_mortgage: 'האם יש משכנתא על הנכס הקיים?',
  imp_exist_mt_bank: 'בנק המשכנתא',
  imp_exist_mt_balance: 'יתרת המשכנתא (ש"ח)',
  imp_exist_mt_monthly: 'תשלום חודשי (ש"ח)',
  imp_exist_pledged: 'האם הנכס משועבד לגוף אחר?',
  imp_exist_pledged_detail: 'פרט שעבוד',
  imp_exist_rented: 'האם הנכס מושכר?',
  imp_exist_rent_amount: 'סכום שכירות (ש"ח)',
  imp_sale_listed: 'האם הנכס מוצע למכירה?',
  imp_sale_signed: 'האם נחתם חוזה מכירה?',
  imp_sale_price: 'מחיר המכירה המוסכם (ש"ח)',
  imp_sale_sign_date: 'תאריך חתימת חוזה מכירה',
  imp_sale_funds_date: 'תאריך קבלת כספי המכירה',
  imp_sale_dep: 'האם שולמה מקדמה?',
  imp_sale_timing: 'מועד מכירה משוער',
  imp_sale_net: 'תמורה נטו לאחר פירעון משכנתא (ש"ח)',
  imp_sale_repay_mt: 'האם תפרע המשכנתא הקיימת ממכירת הנכס?',
  imp_sale_as_equity: 'האם תמורת המכירה תשמש הון עצמי?',
  imp_bridge: 'האם נדרשת הלוואת גישור?',
  imp_bridge_amount: 'סכום הלוואת גישור (ש"ח)',
  imp_mt_portability: 'האם מתוכנן ניוד משכנתא?',
  imp_grace: 'האם מבוקש גרייס?',
  imp_grace_detail: 'פרט גרייס',
  imp_time_gap: 'האם צפוי פער זמנים בין מכירה לרכישה?',
  imp_time_gap_months: 'כמה חודשים פער משוער?',
  imp_new_prop_type: 'סוג הנכס החדש',
  imp_new_prop_status: 'מצב הנכס החדש',
  imp_new_deal_type: 'סוג העסקה',
  imp_new_city: 'עיר הנכס החדש',
  imp_new_street: 'רחוב',
  imp_new_house_num: 'מספר בית',
  imp_new_apt_num: 'מספר דירה',
  imp_new_price: 'מחיר הנכס החדש (ש"ח)',
  imp_new_mortgage_req: 'סכום המשכנתא המבוקש (ש"ח)',
  imp_new_contract_signed: 'האם נחתם חוזה?',
  imp_new_contract_date: 'תאריך חתימת חוזה',
  imp_new_advance_paid: 'האם שולמה מקדמה?',
  imp_new_advance_amount: 'סכום המקדמה (ש"ח)',
  imp_new_advance_date: 'תאריך תשלום מקדמה',
  imp_new_key_date: 'תאריך קבלת מפתח',
  imp_new_payment_sched: 'האם יש לוח תשלומים?',
  imp_new_payment_sched_detail: 'פרט לוח תשלומים',
  imp_eq_amount: 'סכום ההון העצמי (ש"ח)',
  imp_eq_source: 'מקורות ההון העצמי',
  imp_eq_gift: 'האם חלק מההון הוא מתנה?',
  imp_eq_gift_name: 'שם נותן המתנה',
  imp_eq_gift_relation: 'קרבה לנותן המתנה',
  imp_eq_gift_amount: 'סכום המתנה (ש"ח)',
  imp_eq_external: 'האם יש מממן חיצוני?',
  imp_eq_external_funder: 'שם המממן החיצוני',
  imp_eq_external_amount: 'סכום מהמממן (ש"ח)',
  imp_bkr_exists: 'האם יש מתווך?',
  imp_bkr_fee: 'עמלת מתווך (%)',
  imp_law_exists: 'האם יש עורך דין?',
  imp_law_name: 'שם עורך הדין',
  imp_law_phone: 'טלפון עורך הדין',
  imp_apr_existing: 'האם בוצעה שמאות לנכס הקיים?',
  imp_apr_value: 'שווי שמאות (ש"ח)',
  imp_eligibility: 'האם יש זכאות?',
  doc_imp_taboo: 'נסח טאבו / אישור זכויות',
  doc_imp_mt_balance: 'דוח יתרה לפירעון',
  doc_imp_sale_contract: 'חוזה מכירה',
  doc_imp_buy_contract: 'חוזה רכישה',
  doc_imp_payments: 'אסמכתאות תשלומים',
  doc_imp_appraisal: 'שמאות',
  doc_imp_extra: 'מסמכים נוספים',
  refi_prop_type: 'סוג הנכס למחזור',
  refi_prop_city: 'עיר / ישוב',
  refi_prop_street: 'רחוב',
  refi_prop_house_num: 'מספר בית',
  refi_prop_apt_num: 'מספר דירה',
  refi_prop_value: 'שווי הנכס (ש"ח)',
  refi_prop_appraisal: 'האם בוצעה שמאות?',
  refi_prop_appraisal_value: 'שווי שמאות (ש"ח)',
  refi_prop_rented: 'האם הנכס מושכר?',
  refi_prop_rent_amount: 'שכירות חודשית (ש"ח)',
  refi_mt_bank: 'בנק המשכנתא הקיימת',
  refi_mt_balance: 'יתרת המשכנתא (ש"ח)',
  refi_mt_monthly: 'תשלום חודשי נוכחי (ש"ח)',
  refi_mt_borrowers: 'כמה לווים במשכנתא הקיימת?',
  refi_mt_multi: 'האם יש מספר מסלולים?',
  refi_mt_multi_detail: 'פרט מסלולים',
  refi_type: 'סוג המחזור',
  refi_goals: 'מטרות המחזור',
  refi_desired_monthly: 'תשלום חודשי רצוי לאחר מחזור (ש"ח)',
  refi_has_balance_report: 'האם יש דוח יתרה?',
  refi_has_tracks_report: 'האם יש דוח מסלולים?',
  refi_prepay_penalty: 'האם יש עמלת פירעון מוקדם?',
  refi_prepay_penalty_amount: 'סכום עמלת פירעון מוקדם (ש"ח)',
  refi_extra_funds: 'האם נדרשים כספים נוספים מעבר למחזור?',
  refi_extra_funds_amount: 'סכום כספים נוספים (ש"ח)',
  refi_eligibility: 'האם יש זכאות?',
  refi_guarantors: 'האם יש ערבים במשכנתא הקיימת?',
  refi_guarantors_count: 'כמה ערבים?',
  refi_income_change: 'האם חל שינוי בהכנסה?',
  refi_income_change_detail: 'פרט שינוי הכנסה',
  refi_other_loans: 'האם יש הלוואות נוספות?',
  refi_other_loans_monthly: 'סה"כ תשלומי הלוואות נוספות (ש"ח)',
  refi_other_loans_consolidate: 'האם מעוניין לאחד הלוואות?',
  doc_refi_balance_report: 'דוח יתרה לפירעון',
  doc_refi_tracks_report: 'דוח מסלולים',
  doc_refi_bank_statements: 'דפי בנק',
  doc_refi_payslips: 'תלושי שכר',
  doc_refi_appraisal: 'שמאות',
  doc_refi_extra: 'מסמכים נוספים',
  rex_prop_type: 'סוג הנכס',
  rex_prop_city: 'עיר / ישוב',
  rex_prop_street: 'רחוב',
  rex_prop_house_num: 'מספר בית',
  rex_prop_apt_num: 'מספר דירה',
  rex_prop_value: 'שווי הנכס (ש"ח)',
  rex_prop_appraisal: 'האם בוצעה שמאות?',
  rex_prop_appraisal_value: 'שווי שמאות (ש"ח)',
  rex_prop_rented: 'האם הנכס מושכר?',
  rex_prop_rent_amount: 'שכירות חודשית (ש"ח)',
  rex_mt_bank: 'בנק המשכנתא הקיימת',
  rex_mt_balance: 'יתרת המשכנתא (ש"ח)',
  rex_mt_monthly: 'תשלום חודשי (ש"ח)',
  rex_mt_borrowers: 'כמה לווים במשכנתא?',
  rex_mt_multi: 'האם יש מספר מסלולים?',
  rex_mt_multi_detail: 'פרט מסלולים',
  rex_refi_type: 'סוג המחזור',
  rex_refi_goals: 'מטרות המחזור',
  rex_expand_amount: 'סכום ההגדלה המבוקש (ש"ח)',
  rex_expand_net: 'סכום נטו לאחר פירעון (ש"ח)',
  rex_expand_purpose: 'מטרת ההגדלה',
  rex_expand_purpose_other: 'פרט מטרה אחרת',
  rex_expand_single_purpose: 'האם כל הסכום למטרה אחת?',
  rex_expand_split_detail: 'פרט חלוקת המטרות',
  rex_expand_timing: 'מועד הצורך בכספים',
  rex_expand_monthly_limit: 'האם יש מגבלה על תשלום חודשי?',
  rex_expand_monthly_max: 'תשלום חודשי מקסימלי (ש"ח)',
  rex_expand_loan_payoff: 'האם חלק מהכסף לפירעון הלוואה?',
  rex_expand_loan_payoff_amount: 'סכום לפירעון הלוואה (ש"ח)',
  rex_expand_has_docs: 'האם יש מסמכים לתכנית השיפוץ?',
  rex_extra_funds: 'האם נדרשים כספים נוספים?',
  rex_extra_funds_amount: 'סכום כספים נוספים (ש"ח)',
  rex_eligibility: 'האם יש זכאות?',
  rex_guarantors: 'האם יש ערבים?',
  rex_guarantors_count: 'כמה ערבים?',
  rex_income_change: 'האם חל שינוי בהכנסה?',
  rex_income_change_detail: 'פרט שינוי הכנסה',
  rex_other_loans: 'האם יש הלוואות נוספות?',
  rex_other_loans_monthly: 'סה"כ תשלומי הלוואות (ש"ח)',
  rex_has_balance_report: 'האם יש דוח יתרה?',
  rex_has_tracks_report: 'האם יש דוח מסלולים?',
  rex_prepay_penalty: 'האם יש עמלת פירעון מוקדם?',
  rex_prepay_penalty_amount: 'סכום עמלת פירעון (ש"ח)',
  doc_rex_balance_report: 'דוח יתרה לפירעון',
  doc_rex_tracks_report: 'דוח מסלולים',
  doc_rex_bank_statements: 'דפי בנק',
  doc_rex_payslips: 'תלושי שכר',
  doc_rex_appraisal: 'שמאות',
  doc_rex_purpose_docs: 'מסמכי מטרת ההגדלה',
};

// ── Complete form structure ───────────────────────────────────────────────────
// Format: [type, id, required, options_csv_or_null]
const FORM_STRUCTURE = [
  ['radio','b_count','1','1,2,3,4'],
  ['radio','guar_exists','0','כן,לא'],
  ['PAGE_BREAK','borrower','לווה 1 — פרטים אישיים',null],
  ['text','b1_fname','0',null],
  ['text','b1_lname','0',null],
  ['text','b1_id','0',null],
  ['date','b1_dob','0',null],
  ['radio','b1_gender','0','זכר,נקבה'],
  ['radio','b1_marital','0','רווק/ה,נשוי/אה,גרוש/ה,אלמן/ה'],
  ['text','b1_children','0',null],
  ['text','b1_phone','0',null],
  ['text','b1_email','0',null],
  ['text','b1_address','0',null],
  ['text','b1_city','0',null],
  ['text','b1_zip','0',null],
  ['radio','b1_citizen','0','אזרח ישראלי,תושב קבע,אחר'],
  ['text','b1_passno','0',null],
  ['radio','b1_separation','0','כן,לא'],
  ['radio','b1_poa','0','כן,לא'],
  ['PAGE_BREAK','borrower','לווה 1 — תעסוקה והכנסות',null],
  ['radio','b1_employ_status','0','שכיר,עצמאי,שכיר+עצמאי,פנסיונר,לא עובד'],
  ['radio','b1_employ_type','0','מגזר פרטי,מגזר ציבורי,מגזר צה"ל,לא רלוונטי'],
  ['text','b1_employer','0',null],
  ['text','b1_seniority','0',null],
  ['text','b1_income','0',null],
  ['radio','b1_extra_income','0','כן,לא'],
  ['textarea','b1_extra_detail','0',null],
  ['radio','b1_miluim','0','כן,לא'],
  ['radio','b1_pension','0','כן,לא'],
  ['text','b1_pension_amt','0',null],
  ['radio','b1_foreign_income','0','כן,לא'],
  ['radio','b1_alimony','0','כן,לא'],
  ['text','b1_alimony_amt','0',null],
  ['radio','b1_income_change','0','כן,לא'],
  ['textarea','b1_income_change_detail','0',null],
  ['text','b1_bank','0',null],
  ['text','b1_account','0',null],
  ['PAGE_BREAK','borrower','מסמכים — לווה 1',null],
  ['file','doc_b1_id','0',null],
  ['file','doc_b1_salary','0',null],
  ['file','doc_b1_bank','0',null],
  ['PAGE_BREAK','','פרטי הערב',null],
  ['text','guar_fname','0',null],
  ['text','guar_lname','0',null],
  ['text','guar_id','0',null],
  ['text','guar_phone','0',null],
  ['text','guar_email','0',null],
  ['text','guar_relation','0',null],
  ['PAGE_BREAK','','מסמכים — ערב',null],
  ['file','doc_guar_id','0',null],
  ['PAGE_BREAK','','הלוואות קיימות',null],
  ['radio','ln1_exists','0','כן,לא'],
  ['text','ln1_lender','0',null],
  ['text','ln1_balance','0',null],
  ['text','ln1_monthly','0',null],
  ['date','ln1_end_date','0',null],
  ['text','ln1_purpose','0',null],
  ['PAGE_BREAK','','הלוואה 2',null],
  ['radio','ln2_exists','0','כן,לא'],
  ['PAGE_BREAK','','הלוואה 2 — פרטים',null],
  ['text','ln2_lender','0',null],
  ['text','ln2_balance','0',null],
  ['text','ln2_monthly','0',null],
  ['date','ln2_end_date','0',null],
  ['text','ln2_purpose','0',null],
  ['PAGE_BREAK','','הלוואה 3',null],
  ['radio','ln3_exists','0','כן,לא'],
  ['PAGE_BREAK','','הלוואה 3 — פרטים',null],
  ['text','ln3_lender','0',null],
  ['text','ln3_balance','0',null],
  ['text','ln3_monthly','0',null],
  ['date','ln3_end_date','0',null],
  ['text','ln3_purpose','0',null],
  ['PAGE_BREAK','','הלוואה 4',null],
  ['radio','ln4_exists','0','כן,לא'],
  ['PAGE_BREAK','','הלוואה 4 — פרטים',null],
  ['text','ln4_lender','0',null],
  ['text','ln4_balance','0',null],
  ['text','ln4_monthly','0',null],
  ['date','ln4_end_date','0',null],
  ['text','ln4_purpose','0',null],
  ['PAGE_BREAK','','משכנתאות קיימות',null],
  ['radio','mt1_exists','0','כן,לא'],
  ['text','mt1_bank','0',null],
  ['text','mt1_balance','0',null],
  ['text','mt1_monthly','0',null],
  ['date','mt1_end_date','0',null],
  ['text','mt1_address','0',null],
  ['PAGE_BREAK','','משכנתא 2',null],
  ['radio','mt2_exists','0','כן,לא'],
  ['PAGE_BREAK','','משכנתא 2 — פרטים',null],
  ['text','mt2_bank','0',null],
  ['text','mt2_balance','0',null],
  ['text','mt2_monthly','0',null],
  ['date','mt2_end_date','0',null],
  ['text','mt2_address','0',null],
  ['PAGE_BREAK','','משכנתא 3',null],
  ['radio','mt3_exists','0','כן,לא'],
  ['PAGE_BREAK','','משכנתא 3 — פרטים',null],
  ['text','mt3_bank','0',null],
  ['text','mt3_balance','0',null],
  ['text','mt3_monthly','0',null],
  ['date','mt3_end_date','0',null],
  ['text','mt3_address','0',null],
  ['text','cc_count','0',null],
  ['text','cc_limit','0',null],
  ['text','cc_balance','0',null],
  ['radio','guarantee_given','0','כן,לא'],
  ['textarea','guarantee_detail','0',null],
  ['radio','balloon_loan','0','כן,לא'],
  ['textarea','balloon_detail','0',null],
  ['PAGE_BREAK','','עיקולים, הגבלות והליכים',null],
  ['radio','seizure','0','כן,לא'],
  ['textarea','seizure_detail','0',null],
  ['radio','bank_restrict','0','כן,לא'],
  ['textarea','bank_restrict_detail','0',null],
  ['radio','insolvency','0','כן,לא'],
  ['radio','enforcement','0','כן,לא'],
  ['textarea','enforcement_detail','0',null],
  ['radio','debt_arrange','0','כן,לא'],
  ['textarea','debt_arrange_detail','0',null],
  ['radio','bounced_checks','0','כן,לא'],
  ['radio','credit_denied','0','כן,לא'],
  ['radio','legal_proc','0','כן,לא'],
  ['textarea','legal_proc_detail','0',null],
  ['PAGE_BREAK','','מסמכים והצהרה',null],
  ['file','doc_extra','0',null],
  ['checkbox','declaration','0',null],
  ['PAGE_BREAK','','סוג ההלוואה',null],
  ['radio','loan_type','0','רכישה ראשונה — דירת מגורים,רכישה ראשונה — קרקע,רכישה להשקעה,משפרי דיור,מחזור ללא הגדלה,מחזור עם הגדלה,בנייה עצמית,רכישת מגרש / קרקע חקלאית,פינוי בינוי,עסקת קומבינציה,הלוואת גישור,מחזור חלקי,הלוואת בלון'],
  ['PAGE_BREAK','','פרטי הנכס',null],
  ['radio','prop_type','0',"דירה,דירת גן,בית פרטי,קוטג',פנטהאוז,מסחרי,אחר"],
  ['radio','prop_status','0','חדש,יד שנייה,על הנייר'],
  ['radio','prop_deal_type','0','לא מוגדר,ידוע'],
  ['text','prop_city','0',null],
  ['text','prop_street','0',null],
  ['text','prop_house_num','0',null],
  ['text','prop_apt_num','0',null],
  ['text','prop_floor','0',null],
  ['text','prop_floors_total','0',null],
  ['text','prop_rooms','0',null],
  ['text','prop_built_area','0',null],
  ['text','prop_balcony_area','0',null],
  ['text','prop_garden_area','0',null],
  ['radio','prop_parking','0','כן,חנייה שכורה,אין חנייה,מקום חנייה מהוון'],
  ['radio','prop_storage','0','כן,לא'],
  ['radio','prop_elevator','0','כן,לא'],
  ['text','prop_year_built','0',null],
  ['radio','prop_registration','0','טאבו,מנהל,חברה משכנת,לא ידוע'],
  ['checkbox','prop_rights','0','כן,חכירה,בנייה עצמית,מינהל,ירושה,אחר'],
  ['radio','prop_rented','0','כן,לא,לא ידוע'],
  ['radio','prop_violations','0','כן,לא,לא ידוע'],
  ['textarea','prop_violations_detail','0',null],
  ['PAGE_BREAK','','פרטי העסקה',null],
  ['radio','deal_seller_type','0','יזם פרטי,קבלן,רשות מקרקעי ישראל,חברה ממשלתית,אחר'],
  ['text','deal_price','0',null],
  ['text','deal_mortgage_req','0',null],
  ['radio','deal_contract_signed','0','כן,לא'],
  ['date','deal_contract_date','0',null],
  ['radio','deal_conditions','0','כן,לא,לא ידוע'],
  ['textarea','deal_conditions_detail','0',null],
  ['radio','deal_advance_paid','0','כן,לא'],
  ['text','deal_advance_amount','0',null],
  ['date','deal_advance_date','0',null],
  ['date','deal_key_date','0',null],
  ['radio','deal_payment_sched','0','כן,לא'],
  ['textarea','deal_payment_sched_detail','0',null],
  ['radio','deal_status','0','לפני חוזה,נחתם חוזה,שולם מקדמה,קיבלו מפתח בתאריך,יש תאריך מוסכם,מועד גמיש'],
  ['PAGE_BREAK','','הון עצמי ומקורות מימון',null],
  ['text','eq_amount','0',null],
  ['checkbox','eq_source','0','חסכונות,מכירת נכס,מתנה מהורים,ירושה,השקעות,אחר'],
  ['radio','eq_gift','0','כן,לא'],
  ['text','eq_gift_name','0',null],
  ['text','eq_gift_relation','0',null],
  ['text','eq_gift_amount','0',null],
  ['radio','eq_bridge','0','כן,לא'],
  ['text','eq_bridge_amount','0',null],
  ['radio','eq_external','0','כן,לא'],
  ['text','eq_external_funder','0',null],
  ['text','eq_external_amount','0',null],
  ['radio','eq_prop_sale_dep','0','כן,לא'],
  ['textarea','eq_prop_sale_detail','0',null],
  ['PAGE_BREAK','','גורמים מלווים ושמאות',null],
  ['radio','bkr_exists','0','כן,לא'],
  ['text','bkr_fee','0',null],
  ['radio','law_exists','0','כן,לא'],
  ['text','law_name','0',null],
  ['text','law_phone','0',null],
  ['radio','apr_done','0','כן,לא'],
  ['text','apr_value','0',null],
  ['radio','apr_eligibility','0','כן,לא,לא ידוע'],
  ['radio','apr_urgent','0','כן,לא'],
  ['PAGE_BREAK','','מסמכים — רכישת נכס',null],
  ['file','doc_lrm_contract','0',null],
  ['file','doc_lrm_taboo','0',null],
  ['file','doc_lrm_payments','0',null],
  ['file','doc_lrm_appraisal','0',null],
  ['file','doc_lrm_eligibility','0',null],
  ['file','doc_lrm_extra','0',null],
  ['PAGE_BREAK','','פרטי הנכס — השקעה',null],
  ['radio','inv_prop_type','0',"דירה,דירת גן,בית פרטי,קוטג',פנטהאוז,מסחרי,נכס מסחרי,אחר"],
  ['radio','inv_prop_status','0','חדש,יד שנייה,על הנייר'],
  ['radio','inv_prop_deal_type','0','לא מוגדר,ידוע'],
  ['text','inv_prop_city','0',null],
  ['text','inv_prop_street','0',null],
  ['text','inv_prop_house_num','0',null],
  ['text','inv_prop_apt_num','0',null],
  ['text','inv_prop_rooms','0',null],
  ['text','inv_prop_built_area','0',null],
  ['radio','inv_prop_parking','0','כן,חנייה שכורה,אין חנייה,מקום חנייה מהוון'],
  ['radio','inv_prop_storage','0','כן,לא'],
  ['radio','inv_prop_elevator','0','כן,לא'],
  ['radio','inv_prop_rented','0','כן,לא,לא ידוע'],
  ['text','inv_prop_rent_amount','0',null],
  ['radio','inv_prop_violations','0','כן,לא,לא ידוע'],
  ['textarea','inv_prop_violations_detail','0',null],
  ['PAGE_BREAK','','פרטי העסקה — השקעה',null],
  ['radio','inv_deal_seller_type','0','יזם פרטי,קבלן,רשות מקרקעי ישראל,חברה ממשלתית,אחר'],
  ['text','inv_deal_price','0',null],
  ['text','inv_deal_mortgage_req','0',null],
  ['radio','inv_deal_contract_signed','0','כן,לא'],
  ['date','inv_deal_contract_date','0',null],
  ['radio','inv_deal_advance_paid','0','כן,לא'],
  ['text','inv_deal_advance_amount','0',null],
  ['date','inv_deal_advance_date','0',null],
  ['date','inv_deal_key_date','0',null],
  ['radio','inv_deal_payment_sched','0','כן,לא'],
  ['textarea','inv_deal_payment_sched_detail','0',null],
  ['PAGE_BREAK','','פרטי ההשקעה',null],
  ['radio','inv_rental_intent','0','כן,לא'],
  ['text','inv_expected_rent','0',null],
  ['radio','inv_purpose','0','השכרה לטווח ארוך,השכרה קצרת,השבחה ומכירה מהירה,השבחה ומכירה ארוך,החזקה בלבד'],
  ['radio','inv_other_props','0','כן,לא'],
  ['text','inv_other_props_count','0',null],
  ['radio','inv_other_props_mortgage','0','כן,לא'],
  ['text','inv_other_props_monthly','0',null],
  ['radio','inv_via_company','0','כן,לא'],
  ['text','inv_company_name','0',null],
  ['text','inv_company_id','0',null],
  ['radio','inv_partners','0','כן,לא'],
  ['text','inv_partners_count','0',null],
  ['radio','inv_registration_name','0','פרטי,שם אחר,חברה,משותף'],
  ['PAGE_BREAK','','הון עצמי ומקורות מימון — השקעה',null],
  ['text','inv_eq_amount','0',null],
  ['checkbox','inv_eq_source','0','חסכונות,מכירת נכס,מתנה מהורים,ירושה,השקעות,אחר'],
  ['radio','inv_eq_gift','0','כן,לא'],
  ['text','inv_eq_gift_name','0',null],
  ['text','inv_eq_gift_relation','0',null],
  ['text','inv_eq_gift_amount','0',null],
  ['radio','inv_eq_bridge','0','כן,לא'],
  ['text','inv_eq_bridge_amount','0',null],
  ['radio','inv_eq_external','0','כן,לא'],
  ['text','inv_eq_external_funder','0',null],
  ['text','inv_eq_external_amount','0',null],
  ['PAGE_BREAK','','גורמים מלווים ושמאות — השקעה',null],
  ['radio','inv_bkr_exists','0','כן,לא'],
  ['text','inv_bkr_fee','0',null],
  ['radio','inv_law_exists','0','כן,לא'],
  ['text','inv_law_name','0',null],
  ['text','inv_law_phone','0',null],
  ['radio','inv_apr_done','0','כן,לא'],
  ['text','inv_apr_value','0',null],
  ['PAGE_BREAK','','מסמכים — רכישת נכס להשקעה',null],
  ['file','doc_inv_contract','0',null],
  ['file','doc_inv_taboo','0',null],
  ['file','doc_inv_payments','0',null],
  ['file','doc_inv_appraisal','0',null],
  ['file','doc_inv_rental','0',null],
  ['file','doc_inv_extra','0',null],
  ['PAGE_BREAK','','הנכס הקיים',null],
  ['radio','imp_exist_prop_type','0',"דירה,דירת גן,בית פרטי,קוטג',פנטהאוז,מסחרי,אחר"],
  ['text','imp_exist_city','0',null],
  ['text','imp_exist_street','0',null],
  ['text','imp_exist_house_num','0',null],
  ['text','imp_exist_apt_num','0',null],
  ['text','imp_exist_value','0',null],
  ['radio','imp_exist_mortgage','0','כן,לא'],
  ['text','imp_exist_mt_bank','0',null],
  ['text','imp_exist_mt_balance','0',null],
  ['text','imp_exist_mt_monthly','0',null],
  ['radio','imp_exist_pledged','0','כן,לא'],
  ['textarea','imp_exist_pledged_detail','0',null],
  ['radio','imp_exist_rented','0','כן,לא'],
  ['text','imp_exist_rent_amount','0',null],
  ['PAGE_BREAK','','מכירת הנכס הקיים',null],
  ['radio','imp_sale_listed','0','כן,לא'],
  ['radio','imp_sale_signed','0','כן,לא'],
  ['text','imp_sale_price','0',null],
  ['date','imp_sale_sign_date','0',null],
  ['date','imp_sale_funds_date','0',null],
  ['radio','imp_sale_dep','0','כן,לא'],
  ['radio','imp_sale_timing','0','כבר מכרתי,עד 6 חודשים,6-12 חודשים,מעל 12 חודשים,לא ידוע'],
  ['text','imp_sale_net','0',null],
  ['radio','imp_sale_repay_mt','0','כן,לא,חלקי'],
  ['radio','imp_sale_as_equity','0','כן,לא,חלקי'],
  ['radio','imp_bridge','0','כן,לא'],
  ['text','imp_bridge_amount','0',null],
  ['radio','imp_mt_portability','0','כן,לא,לא רלוונטי'],
  ['radio','imp_grace','0','כן,לא'],
  ['textarea','imp_grace_detail','0',null],
  ['radio','imp_time_gap','0','כן,לא'],
  ['text','imp_time_gap_months','0',null],
  ['PAGE_BREAK','','הנכס החדש',null],
  ['radio','imp_new_prop_type','0',"דירה,דירת גן,בית פרטי,קוטג',פנטהאוז,מסחרי,אחר"],
  ['radio','imp_new_prop_status','0','חדש,יד שנייה,על הנייר'],
  ['radio','imp_new_deal_type','0','לא מוגדר,ידוע'],
  ['text','imp_new_city','0',null],
  ['text','imp_new_street','0',null],
  ['text','imp_new_house_num','0',null],
  ['text','imp_new_apt_num','0',null],
  ['text','imp_new_price','0',null],
  ['text','imp_new_mortgage_req','0',null],
  ['radio','imp_new_contract_signed','0','כן,לא'],
  ['date','imp_new_contract_date','0',null],
  ['radio','imp_new_advance_paid','0','כן,לא'],
  ['text','imp_new_advance_amount','0',null],
  ['date','imp_new_advance_date','0',null],
  ['date','imp_new_key_date','0',null],
  ['radio','imp_new_payment_sched','0','כן,לא'],
  ['textarea','imp_new_payment_sched_detail','0',null],
  ['PAGE_BREAK','','הון עצמי ומקורות מימון — משפרי דיור',null],
  ['text','imp_eq_amount','0',null],
  ['checkbox','imp_eq_source','0','תמורת מכירת דירה,חסכונות,מתנה מהורים,ירושה,השקעות,אחר'],
  ['radio','imp_eq_gift','0','כן,לא'],
  ['text','imp_eq_gift_name','0',null],
  ['text','imp_eq_gift_relation','0',null],
  ['text','imp_eq_gift_amount','0',null],
  ['radio','imp_eq_external','0','כן,לא'],
  ['text','imp_eq_external_funder','0',null],
  ['text','imp_eq_external_amount','0',null],
  ['PAGE_BREAK','','גורמים מלווים ושמאות — משפרי דיור',null],
  ['radio','imp_bkr_exists','0','כן,לא'],
  ['text','imp_bkr_fee','0',null],
  ['radio','imp_law_exists','0','כן,לא'],
  ['text','imp_law_name','0',null],
  ['text','imp_law_phone','0',null],
  ['radio','imp_apr_existing','0','כן,לא'],
  ['text','imp_apr_value','0',null],
  ['radio','imp_eligibility','0','כן,לא,לא ידוע'],
  ['PAGE_BREAK','','מסמכים — משפרי דיור',null],
  ['file','doc_imp_taboo','0',null],
  ['file','doc_imp_mt_balance','0',null],
  ['file','doc_imp_sale_contract','0',null],
  ['file','doc_imp_buy_contract','0',null],
  ['file','doc_imp_payments','0',null],
  ['file','doc_imp_appraisal','0',null],
  ['file','doc_imp_extra','0',null],
  ['PAGE_BREAK','','פרטי הנכס — מחזור',null],
  ['radio','refi_prop_type','0',"דירה,דירת גן,בית פרטי,קוטג',פנטהאוז,מסחרי,אחר"],
  ['text','refi_prop_city','0',null],
  ['text','refi_prop_street','0',null],
  ['text','refi_prop_house_num','0',null],
  ['text','refi_prop_apt_num','0',null],
  ['text','refi_prop_value','0',null],
  ['radio','refi_prop_appraisal','0','כן,לא'],
  ['text','refi_prop_appraisal_value','0',null],
  ['radio','refi_prop_rented','0','כן,לא'],
  ['text','refi_prop_rent_amount','0',null],
  ['PAGE_BREAK','','פרטי המשכנתא הקיימת',null],
  ['text','refi_mt_bank','0',null],
  ['text','refi_mt_balance','0',null],
  ['text','refi_mt_monthly','0',null],
  ['radio','refi_mt_borrowers','0','1,2,3+'],
  ['radio','refi_mt_multi','0','כן,לא'],
  ['textarea','refi_mt_multi_detail','0',null],
  ['PAGE_BREAK','','סוג המחזור ומטרות',null],
  ['radio','refi_type','0','מחזור לתנאים טובים,פדיון מוקדם מלא,מחזור עם שינוי'],
  ['checkbox','refi_goals','0','הורדת תשלום חודשי,קיצור תקופה,שינוי ריביות,שינוי מסלול,הפחתת סיכון,שיפור תנאי בניית תמהיל,אחר'],
  ['text','refi_desired_monthly','0',null],
  ['PAGE_BREAK','','נתוני המשכנתא הקיימת',null],
  ['radio','refi_has_balance_report','0','כן,לא'],
  ['radio','refi_has_tracks_report','0','כן,לא'],
  ['radio','refi_prepay_penalty','0','כן,לא,לא ידוע'],
  ['text','refi_prepay_penalty_amount','0',null],
  ['radio','refi_extra_funds','0','כן,לא'],
  ['text','refi_extra_funds_amount','0',null],
  ['PAGE_BREAK','','זכאות, ערבים ושינויים צפויים',null],
  ['radio','refi_eligibility','0','כן,לא,לא ידוע'],
  ['radio','refi_guarantors','0','כן,לא'],
  ['text','refi_guarantors_count','0',null],
  ['radio','refi_income_change','0','כן,לא'],
  ['textarea','refi_income_change_detail','0',null],
  ['radio','refi_other_loans','0','כן,לא'],
  ['text','refi_other_loans_monthly','0',null],
  ['radio','refi_other_loans_consolidate','0','כן,לא'],
  ['PAGE_BREAK','','מסמכים — מחזור משכנתא',null],
  ['file','doc_refi_balance_report','0',null],
  ['file','doc_refi_tracks_report','0',null],
  ['file','doc_refi_bank_statements','0',null],
  ['file','doc_refi_payslips','0',null],
  ['file','doc_refi_appraisal','0',null],
  ['file','doc_refi_extra','0',null],
  ['PAGE_BREAK','','פרטי הנכס — מחזור והגדלה',null],
  ['radio','rex_prop_type','0',"דירה,דירת גן,בית פרטי,קוטג',פנטהאוז,מסחרי,אחר"],
  ['text','rex_prop_city','0',null],
  ['text','rex_prop_street','0',null],
  ['text','rex_prop_house_num','0',null],
  ['text','rex_prop_apt_num','0',null],
  ['text','rex_prop_value','0',null],
  ['radio','rex_prop_appraisal','0','כן,לא'],
  ['text','rex_prop_appraisal_value','0',null],
  ['radio','rex_prop_rented','0','כן,לא'],
  ['text','rex_prop_rent_amount','0',null],
  ['PAGE_BREAK','','פרטי המשכנתא הקיימת — מחזור והגדלה',null],
  ['text','rex_mt_bank','0',null],
  ['text','rex_mt_balance','0',null],
  ['text','rex_mt_monthly','0',null],
  ['radio','rex_mt_borrowers','0','1,2,3+'],
  ['radio','rex_mt_multi','0','כן,לא'],
  ['textarea','rex_mt_multi_detail','0',null],
  ['radio','rex_refi_type','0','מחזור לתנאים טובים,פדיון מוקדם מלא,מחזור עם שינוי'],
  ['checkbox','rex_refi_goals','0','הורדת תשלום חודשי,קיצור תקופה,שינוי ריביות,שינוי מסלול,הפחתת סיכון,שיפור תנאי בניית תמהיל,אחר'],
  ['PAGE_BREAK','','פרטי ההגדלה',null],
  ['text','rex_expand_amount','0',null],
  ['text','rex_expand_net','0',null],
  ['checkbox','rex_expand_purpose','0','שיפוץ ושדרוג,חינוך,רכישה,רפואה,פדיון הלוואות,סגירת כרטיס אשראי,אחר'],
  ['textarea','rex_expand_purpose_other','0',null],
  ['radio','rex_expand_single_purpose','0','כן,לא'],
  ['textarea','rex_expand_split_detail','0',null],
  ['radio','rex_expand_timing','0','מיידי,עד 3 חודשים,3-6 חודשים,מעל 6 חודשים'],
  ['radio','rex_expand_monthly_limit','0','כן,לא'],
  ['text','rex_expand_monthly_max','0',null],
  ['radio','rex_expand_loan_payoff','0','כן,לא'],
  ['text','rex_expand_loan_payoff_amount','0',null],
  ['radio','rex_expand_has_docs','0','כן,לא'],
  ['PAGE_BREAK','','זכאות, ערבים ושינויים — מחזור והגדלה',null],
  ['radio','rex_extra_funds','0','כן,לא'],
  ['text','rex_extra_funds_amount','0',null],
  ['radio','rex_eligibility','0','כן,לא,לא ידוע'],
  ['radio','rex_guarantors','0','כן,לא'],
  ['text','rex_guarantors_count','0',null],
  ['radio','rex_income_change','0','כן,לא'],
  ['textarea','rex_income_change_detail','0',null],
  ['radio','rex_other_loans','0','כן,לא'],
  ['text','rex_other_loans_monthly','0',null],
  ['PAGE_BREAK','','נתוני המשכנתא הקיימת — מחזור והגדלה',null],
  ['radio','rex_has_balance_report','0','כן,לא'],
  ['radio','rex_has_tracks_report','0','כן,לא'],
  ['radio','rex_prepay_penalty','0','כן,לא,לא ידוע'],
  ['text','rex_prepay_penalty_amount','0',null],
  ['PAGE_BREAK','','מסמכים — מחזור והגדלת משכנתא',null],
  ['file','doc_rex_balance_report','0',null],
  ['file','doc_rex_tracks_report','0',null],
  ['file','doc_rex_bank_statements','0',null],
  ['file','doc_rex_payslips','0',null],
  ['file','doc_rex_appraisal','0',null],
  ['file','doc_rex_purpose_docs','0',null],
];

function buildQuestions() {
  const questions = [];
  for (const [type, id, required, optionsCsv] of FORM_STRUCTURE) {
    if (type === 'PAGE_BREAK') {
      // id here is the borrower group, optionsCsv is null, required is the title
      questions.push({
        type: 'PAGE_BREAK',
        id: id || '',
        label: required, // PAGE_BREAK rows: col[2] is the title
        required: false,
        options: [],
      });
    } else {
      const label = LABELS[id] || id;
      const options = optionsCsv ? optionsCsv.split(',') : [];
      questions.push({
        type,
        id,
        label,
        required: required === '1',
        options,
      });
    }
  }
  return questions;
}

async function main() {
  process.stdout.write('Connecting to MongoDB...\n');
  await mongoose.connect(MONGO_URI, {
    serverSelectionTimeoutMS: 15000,
  });
  process.stdout.write('Connected.\n');

  // Fetch existing form
  const form = await Form.findOne({ id: 'e566c32e' });
  if (!form) {
    process.stdout.write('ERROR: Form e566c32e not found in database!\n');
    process.exit(1);
  }
  process.stdout.write(`Found form: "${form.title}" with ${form.questions.length} questions\n`);

  // Build corrected questions
  const questions = buildQuestions();
  const questionCount = questions.filter(q => q.type !== 'PAGE_BREAK').length;

  // Verify Hebrew encoding
  process.stdout.write(`Sample labels check:\n`);
  process.stdout.write(`  [0] ${questions[0].label}\n`);
  process.stdout.write(`  [1] ${questions[1].label}\n`);
  process.stdout.write(`  [2] ${questions[2].label}\n`);

  // Update the form
  form.title = 'שאלון פרטים אישיים';
  form.description = 'שאלון 1-3 — פרטי לווים, נתוני הנכס והעסקה';
  form.questions = questions;
  form.updatedAt = new Date().toISOString();

  // Mark questions as modified (mongoose mixed array)
  form.markModified('questions');
  form.markModified('title');
  form.markModified('description');

  await form.save();
  process.stdout.write(`\nSaved successfully!\n`);

  // Verify by re-fetching
  const saved = await Form.findOne({ id: 'e566c32e' });
  process.stdout.write(`\nVerification — re-fetched form:\n`);
  process.stdout.write(`  title: ${saved.title}\n`);
  process.stdout.write(`  questions count: ${saved.questions.length}\n`);
  process.stdout.write(`  label[0]: ${saved.questions[0] && saved.questions[0].label}\n`);
  process.stdout.write(`  label[1]: ${saved.questions[1] && saved.questions[1].label}\n`);
  process.stdout.write(`  label[2]: ${saved.questions[2] && saved.questions[2].label}\n`);

  const restoredCount = saved.questions.filter(q => q.type !== 'PAGE_BREAK').length;
  process.stdout.write(`\nSUCCESS: ${restoredCount} questions restored\n`);

  await mongoose.disconnect();
}

main().catch(err => {
  process.stdout.write(`ERROR: ${err.message}\n${err.stack}\n`);
  process.exit(1);
});
